dist: trusty
sudo: required
before_install:
  - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty main'
  - sudo apt-get update -qq
  - virtualenv optviewer
  - source optviewer/bin/activate ; pip install pyyaml pygments
install:
  - sudo apt-get install -qq -y clang-4.0 binutils-gold
script:
  - cd thrift; ./bootstrap.sh &&  CXX=clang++-4.0 CC=clang-4.0 CXXFLAGS="-fsave-optimization-record" CFLAGS="-fsave-optimization-record" ./configure && make ; cd -
  - cd cpython; CC=clang-4.0 CFLAGS="-fsave-optimization-record" ./configure --with-optimizations && make ; cd -
  - source optviewer/bin/activate ; ./llvm/utils/opt-viewer/opt-viewer.py -source-dir cpython/ $(find cpython -name '*.yaml') out/
