dist: trusty
compiler: clang
sudo: required

# for kfr:
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - libmpfr-dev
# ^^ for kfr

before_install:
  - wget -nv -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
  - sudo apt-get update -qq
  - virtualenv optviewer
  - source optviewer/bin/activate ; pip install pyyaml pygments
install:
  - sudo apt-get install -qq -y clang-4.0 binutils-gold
script:
  - ./generate_analysis.sh
  - ./deploy.sh

branches:
  only:
  - master
  - dev
