dist: trusty
sudo: required
before_install:
  - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty main'
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq -y clang-4.0 binutils-gold
script:
  - cd cpython; CC=clang-4.0 CFLAGS="-fsave-optimization-record" ./configure --with-optimizations && make ; cd -
  - ./llvm/utils/opt-viewer/opt-viewer.py $(find cpython -name '*.yaml') -source_dir cpython out/
